# Generated by Django 6.0 on 2025-12-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='icon',
            field=models.ImageField(blank=True, upload_to='supplier/'),
        ),
    ]
